version: '3'

services:
  h2ogpt:
    image: ${H2OGPT_RUNTIME}
    restart: always
    shm_size: '2gb'
    ports:
      - '7860:7860'
    volumes:
      - cache:/workspace/.cache
      - save:/workspace/save
    command:
      - /workspace/generate.py
      - --base_model=llama
      - --model_path_llama=${MODEL_PATH_LLAMA}
      - --max_seq_len=4096

volumes:
  cache:
  save:
