version: '3'

services:
  h2ogpt:
    image: ${H2OGPT_RUNTIME}
    restart: always
    shm_size: '2gb'
    ports:
      - '${H2OGPT_PORT}:7860'
    volumes:
      - cache:/workspace/.cache
      - save:/workspace/save
    command:
      - /workspace/generate.py
      - --base_model=${H2OGPT_BASE_MODEL}
      - --use_safetensors=True
      - --prompt_type=llama2
      - --save_dir=/workspace/save/
      - --use_gpu_id=False
      - --score_model=None
      - --max_max_new_tokens=2048
      - --max_new_tokens=1024
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

volumes:
  cache:
  save:
