version: '3'

services:
  h2ogpt:
    image: gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0
    restart: always
    shm_size: '2gb'
    ports:
      - '7860:7860'
    volumes:
      - cache:/workspace/.cache
      - save:/workspace/save
    command:
      - /workspace/generate.py
      - --base_model=h2oai/h2ogpt-4096-llama2-7b-chat
      - --use_safetensors=True
      - --prompt_type=llama2
      - --save_dir=/workspace/save/
      - --use_gpu_id=False
      - --score_model=None
      - --max_max_new_tokens=2048
      - --max_new_tokens=1024
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

volumes:
  cache:
  save:
