apiVersion: v1
kind: Service
metadata:
  name: {{ include "h2ogpt.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "h2ogpt.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.webPort }}
      targetPort: 7860
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "h2ogpt.fullname" . }}-gpt
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "h2ogpt.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.gptPort }}
      targetPort: 8888
  type: NodePort