nameOverride: ""
fullnameOverride: h2ogpt

autoscaling: {}

replicaCount: 1

image:
  repository: gcr.io/vorvan/h2oai/h2ogpt-runtime
  pullPolicy: IfNotPresent

storage:
  size: 128Gi
  class: ebs-csi

config:
  hfModel: h2oai/h2ogpt-gm-oasst1-en-2048-open-llama-7b

podAnnotations: {}

podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

livenessProbe:
    initialDelaySeconds: 600
    periodSeconds: 5
    failureThreshold: 5
    timeoutSeconds: 120
    successThreshold: 1

readinessProbe:
    initialDelaySeconds: 600
    periodSeconds: 5
    failureThreshold: 5
    timeoutSeconds: 1
    successThreshold: 1

service:
  type: NodePort
  webPort: 80
  gptPort: 8888

resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    nvidia.com/gpu: 1

nodeSelector:
  gpt.h2o.ai/provisioner: karpenter

tolerations:
  - key: gpt.h2o.ai/accelerator
    operator: Equal
    value: gpt-gpu
    effect: NoSchedule